### PR TITLE
Implement reference-sense paths

### PR DESCRIPTION
**Pull request by adamnovak**
This allows GBWTGraph to store reference-sense named paths that also have a sample and contig associated with them. They are marked by having `__gbwt_ref` *prepended* to the sample name.

I also refactored the PathMetadata API a bit, and am porting over to the new version in this PR.

### CODE REVIEW

**Comment by adamnovak** [comment]
This is for libhandlegraph with https://github.com/vgteam/libhandlegraph/pull/84

**Comment by jltsiren** [comment]
I think this is introducing a lot of complexity that will be difficult to undo later.

GBZ is supposed to be a representation of a subset of GFA, and GFA only supports named paths and haplotype paths. My idea was that if GFA adds reference paths, I would use GBWT/GBZ tags to support them. By listing the relevant sample names, for example, and then automatically caching the paths with some annotations in the same way as named paths. GBWT sample/contig names were supposed to be opaque, because encoding additional information in strings is complex and error-prone.

GFA parsing should not use the senses at all, because it uses GFA semantics rather than libhandlegraph semantics. Every path parsed as a haplotype, unless there are both named paths and haplotype paths in the file. The reference sense does not exist in the GFA file, so it can't exist in the GBZ file.

**Comment by adamnovak** [comment]
I see how using a list of sample names that are references might be better than the prefix system I put together. I wasn't sure where to put that in a GBWT, but I was just looking through the GBWT code now and saw it has a key-value tag system in there. Would that be the right place maybe? Or did you mean we would want to use a GBZ equivalent of GFA optional tags on paths/walks to mark them as references (and also add tag parsing support)?

Maybe while we're at it we could drop the `__gbwt_ref` magic sample, and just let path names have `sample` set to `index.metadata.sample_names.size()` for a no-sample sentinel?

> The reference sense does not exist in the GFA file, so it can't exist in the GBZ file.

My PR for vg that I'm working on in https://github.com/vgteam/vg/pull/3646 interprets certain paths in the GFA file (namely, P lines and rGFA paths that have names in Erik's [PanSN format](https://github.com/pangenome/PanSN-spec)) as reference sense, and it knows to round-trip them back to GFA as P lines, while still exposing the sample, contig, and phase just like for haplotypes.

It kind of still isn't really a GFA concept, but I'm trying to make it a handlegraph concept. In part I want to do this because it's a much better match for GBZ's internal formats to have an assembly and a contig in your reference, than it is to just have a flat name. It's awkward on the GBWT side to be storing paths for contigs "GRCh38's chr1" and "CHM13's chr1" in the sample "__gbwt_ref", along with paths for sample "NA12940" on contig "chr1".


Should I rip out the reference sense from GBWTGraph and libhandlegraph? Or should I settle for GBWTGraph not being able to represent the same path metadata that other libhandlegraph implementations can represent? Or should I do something else?

**Comment by jltsiren** [comment]
GBWT metadata, GFA W-lines, and PanSN path names all assume that all paths are haplotypes. If we treat all paths as haplotypes, we get something sensible.

The `_gbwt_ref` hack is implemented on top of that assumption. If we see that sample name, we can assume that all paths for that sample have distinct contig names, and we can treat them as named paths. But we can still use them as haplotype paths if we want to.

The tags I mentioned are the key-value structures in `GBWT` and `GBZ` (but not in `GBWTGraph`). The way I imagined it, if `GBWTGraph::cache_named_paths()` sees that a GBWT path could be interpreted as something other than a haplotype path, it stores all the relevant information as a `NamedPath` object. In particular, the object should know what kind of a path we are dealing with. If we see a path with sample name listed in the relevant `GBWT` tag, we store is as a reference path. If not but the sample name is `_gbwt_ref`, we stored it as a named path.

**Pull request merged**
