### PR TITLE
re-enable cmake builds

### PR DESCRIPTION
**Pull request by ekg**
I found that I had to make a few changes to the build to get it to work.

### CODE REVIEW

**Comment by ekg** [comment]
This last update moves to using submodules. That makes cloning a little more complicated but simplifies builds for package managers and also making tarballs of the source tree.

**Comment by jltsiren** [comment]
A few comments:

* You should use the SDSL you added as a GBWT submodule instead of having a second copy.
* Should the GBWT submodule point to `https://github.com/jltsiren/gbwt.git` instead of `https://github.com/ekg/gbwt.git`?
* `deps/mmmulti`, `deps/ips4o`, and `deps/BBHash` are unnecessary. They are probably leftovers from the seqwish file that was used as a base for the cmake build.

**Comment by ekg** [comment]
Yes, I'll make these changes. Also, I was pointing to my repo for testing.

**Comment by ekg** [comment]
I've updated the build and submodule as requested. Let me know if this is good for you.

The CMakeLists.txt could be cleaned up to remove repetition, but it's OK.

**Comment by jltsiren** [comment]
Can you also remove the unnecessary submodules?

**Pull request merged**
