### PR TITLE
Simpler Path Metadata with Reference-Sesne paths

### PR DESCRIPTION
**Pull request by adamnovak**
This replaces #26 and implements reference-sense paths in a different way (by encoding them just like haplotype paths, but adding a tag to the GBWT's header noting what samples ought to have their paths interpreted as reference paths).

For representing this in GFA, I'm using a string-type `RS` tag ("reference samples"), which is the space-separated sample names.

All the code for working with path metadata in GBWTs is also brought out into functions that can be called from vg when we need to work with paths stored in a GBWT but don't have a GBWTGraph object.

### CODE REVIEW

**Comment by adamnovak** [comment]
@jltsiren What do you think of this version?

**Comment by jltsiren** [comment]
@adamnovak It looks ok. I'm going to run some large-scale tests to see if there are any unexpected consequences.

You should now have write access to the repository. You should document the major changes in the "Current version" section at https://github.com/jltsiren/gbwtgraph/wiki/Version-History

**Comment by jltsiren** [comment]
`tests/gfas/example_reference.gfa` is missing from the PR.

**Comment by adamnovak** [comment]
Oops! It should be in there now.

I'll add some changelog to https://github.com/jltsiren/gbwtgraph/wiki/Version-History

**Pull request merged**
