### PR TITLE
Path handle graph implementation

### PR DESCRIPTION
**Pull request by adamnovak**
This makes a `GBWTGraph` a `PathHandleGraph`.

The only thing I'm not quite sure about are empty paths. I think I want to add some tests to make sure they work properly.

### CODE REVIEW

**Comment by jltsiren** [comment]
A few comments:

* GBWT assumes that paths are non-empty to avoid some special cases. This is enforced during construction.
* `sequence_to_path()`, `sequence_is_reverse()`, and `path_to_sequence()` duplicate `gbwt::Path::id()`, `gbwt::Path::is_reverse()`, and `gbwt::Path::encode()`.
* When locating single positions, `locate(edge_type)` and `locate(node_type, size_type)` have less overhead than `locate(SearchState)`.

I have some ideas how to optimize things, but I'll consider them once this has been merged in.

**Comment by adamnovak** [comment]
Hm. vg uses empty paths in the graph as part of the per-allele path system to tell you where the paths are for variants to build the GBWT. I suppose we might not *need* them once we *have* a GBWT, but not having any support for them makes it difficult to round-trip graphs, or to use a VCF for a new sample to add that sample to an existing GBWT.

I just added some tests for them, before seeing your comment, and they seem to work, though maybe their presence breaks the actual search algorithms. `GBWTBuilder::insert` does not actually prohibit you from inserting empty paths; if they really can't be supported in the GBWT we might need to change that in `gbwt`.

Maybe we can represent them as contigs that don't actually have any GBWT threads on them?

I'll see what I can do about the duplicated code and using the more efficient locates.

One thing I noticed in the code is that we have not only `GBWTGraph` but also `CachedGBWTGraph`, and presumably both are going to need the path support. I noticed that `CachedGBWTGraph` doesn't inherit from `GBWTGraph`, with the justification being that virtual methods are slow:

https://github.com/jltsiren/gbwtgraph/blob/1261bb7069748ba750395afb83e384682a92eb15/include/gbwtgraph/cached_gbwtgraph.h#L23-L27

We can have `CachedGBWTGraph` inherit from `GBWTGraph` without using any virtual methods or paying any runtime speed penalty. We just have to not make any methods virtual. Then all the method resolution happens at compile time. (The cost is slightly weird behavior where if you use a `GBWTGraph*` to talk to what turns out to be a `CachedGBWTGraph`, you call the `GBWTGraph::` versions of the methods.) I think I'm going to try and set this up so I don't have to copy-paste all the PathHandleGraph implementations.

**Comment by jltsiren** [comment]
It looks like I removed the checks for empty paths when I implemented `GBWTBuilder`. The GBWT can technically support them (except maybe in locate queries), but I'm not sure if they still break some algorithms or data model assumptions. I'll go over the code to see if we can officially support empty paths.

`CachedGBWTGraph` is fragile and it should only be used with care. It's not thread-safe, and the cache may grow huge because cache handles are guaranteed to be stable. I don't like making it too easy to use `CachedGBWTGraph` in an algorithm that's not aware what it's dealing with. It should not be a `GBWTGraph`, and ideally it would not be a `HandleGraph` either, but that doesn't work with VG algorithms. Maybe it doesn't need `PathHandleGraph` functionality at all.

**Comment by adamnovak** [comment]
OK, I've pushed this up to `d92a592` to address your comments about code duplication and efficienty @jltsiren. If you can sign off that empty paths can be safely stored in the GBWT, and we don't need `CachedGBWTGraph` to be a PathHandleGraph, then I think this will be ready.

**Pull request merged**
